server:
  port: 9111

spring:
  ai:
    ollama:
      base-url: http://127.0.0.1:11434

# Redis
redis:
  sdk:
    config:
      host: 116.205.112.70
      port: 6379
      password: 123456
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true